KME 5110 Add event to action close (SDK Portmone)
kyivstarteam/react-native-ecom-portmone pull request #12
Opened 2020-12-03 08:31 UTC by dimitriib

Added Event Listeners.
Need for tracking when SDK form was closed.

2020-12-03 08:37 UTC, anya-ks commented on android/src/main/java/ua/kyivstar/sdk/portmone/rnecom/PortmoneCardModule.java
> +        Log.d(Constants.PORTMONE_TAG, "asd initCardPayment");
аяй

2020-12-03 08:39 UTC, anya-ks commented on index.d.ts
> +        addListener<K extends SupportedEventTypes>(
не вижу SupportedEventTypes

2020-12-03 08:40 UTC, anya-ks commented
Плюс, допиши плз в доки, что у нас есть такой листенер.

2020-12-03 08:51 UTC, dimitriib commented on android/src/main/java/ua/kyivstar/sdk/portmone/rnecom/PortmoneCardModule.java
> +        Log.d(Constants.PORTMONE_TAG, "asd initCardPayment");
упс

2020-12-03 09:00 UTC, yevheniionipko requested changes

2020-12-03 09:00 UTC, yevheniionipko commented on ios/PortmoneCardModule.swift
> +    override static func moduleName() -> String! {
не уверен что тут нужен override) проверь плз

2020-12-03 09:00 UTC, yevheniionipko commented on ios/PortmoneCardModule.swift
> +}
зачем ты вынес это в экстеншон? я думаю не стоит выносить эти методы

2020-12-03 09:00 UTC, yevheniionipko commented on ios/PortmoneCardViewController.swift
> +      }
поправь код)

2020-12-03 09:00 UTC, yevheniionipko commented on ios/PortmoneCardModule.swift
> +}
создай файл константс и туда это велью

2020-12-03 09:00 UTC, yevheniionipko commented on index.js
> +  addListener(eventType, callback = () => {}) {
сделай просто не обязательным callback

2020-12-03 09:00 UTC, yevheniionipko commented on android/src/main/java/ua/kyivstar/sdk/portmone/rnecom/PortmoneCardModule.java
> +                    .emit(eventName, value);
не вижу места в джава коде где ты удаляешь этот listener

2020-12-03 09:00 UTC, yevheniionipko commented on android/src/main/java/ua/kyivstar/sdk/portmone/rnecom/PortmoneCardModule.java
> +    private static final String ON_FORM_DISMISS_EVENT = "onFormViewDissmissed";
тоже создай файлик константс и туда же эти константы

2020-12-03 09:04 UTC, dimitriib commented on ios/PortmoneCardModule.swift
> +    override static func moduleName() -> String! {
k

2020-12-03 09:05 UTC, dimitriib commented on ios/PortmoneCardViewController.swift
> +      }
k

2020-12-03 09:06 UTC, dimitriib commented on index.js
> +  addListener(eventType, callback = () => {}) {
ну, он по факту обязательный

2020-12-03 12:37 UTC, anya-ks commented on ios/PortmoneCardModule.swift
> +}
Почему не стоит?

2020-12-03 14:13 UTC, yevheniionipko commented on ios/PortmoneCardModule.swift
> +}
давай тогда вынесем все в екстеншен) какой принцип отбора что те методы попали в экстеншон а те нет?

2020-12-03 14:14 UTC, yevheniionipko commented on index.js
> +  addListener(eventType, callback = () => {}) {
угу но ты прописал по умолчанию значение () => {}

2020-12-03 14:15 UTC, anya-ks commented on ios/PortmoneCardModule.swift
> +}
Ты так и не ответил почему ты думаешь что в екстеншене этому коду не место)

2020-12-03 14:16 UTC, yevheniionipko commented on ios/PortmoneCardModule.swift
> +}
выше ответил))) какой принцип отбора? не вижу смысла разделять методы

2020-12-03 14:26 UTC, anya-ks commented on ios/PortmoneCardModule.swift
> +}
Нет, так не работает, по сути, ты предлагаешь сделать по другому, хотелось бы услышать конкретику, почему так не делать, и почему сделать так как ты предлагаешь)

2020-12-03 14:31 UTC, yevheniionipko requested changes

2020-12-03 14:31 UTC, yevheniionipko commented on ios/PortmoneCardModule.swift
> +}
Пришли к тому что сделай так => 

`extension PortmoneCardModule: RCTEventEmitter {
  override func startObserving() {
    self.hasRegisteredEvents = true
  }

  override func stopObserving() {
    self.hasRegisteredEvents = false
  }

  override func sendEvent(withName name: String!, body: Any!) {
    if (hasRegisteredEvents) {
      super.sendEvent(withName: name, body: body)
    }
  }
}`

2020-12-04 10:29 UTC, yevheniionipko approved these changes

2020-12-04 10:58 UTC, anya-ks approved these changes

2020-12-10 15:18 UTC, merged